[general]
import = [
  "~/.config/alacritty/catppuccin-latte.toml"
]

[font]
size = 16
normal = { family = "FiraCode Nerd Font", style = "Regular" }

[window]
option_as_alt = "Both"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
action = "SelectNextTab"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
action = "SelectPreviousTab"
key = "Left"
mods = "Command"
