tap "homebrew/bundle"
tap "homebrew/cask", "https://mirrors.ustc.edu.cn/homebrew-cask.git"
tap "homebrew/core", "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
tap "homebrew/services"
tap "openresty/brew"
tap "universal-ctags/universal-ctags"
brew "axel"
brew "bat"
brew "boost@1.59"
brew "boost-python@1.59"
brew "caddy"
brew "cmake"
brew "composer"
brew "diff-so-fancy"
brew "dnsmasq", restart_service: true
brew "exa"
brew "fd"
brew "harfbuzz"
brew "snappy", link: false
brew "tesseract"
brew "fzf"
brew "gcc"
brew "glog"
brew "szip"
brew "hdf5"
brew "htop"
brew "hyperfine"
brew "inetutils"
brew "jq"
brew "leveldb"
brew "librdkafka"
brew "libuv"
brew "lmdb"
brew "lua"
brew "lua@5.1"
brew "maven"
brew "mdcat"
brew "mysql@5.7"
brew "ncdu"
brew "node"
brew "python"
brew "numpy", link: false
brew "opencv@3"
brew "redis", restart_service: true
brew "ripgrep"
brew "scala"
brew "snzip"
brew "tealdeer"
brew "the_silver_searcher"
brew "tmux"
brew "watchman"
brew "wrk"
brew "yarn"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "openresty/brew/openresty"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "appcleaner"
cask "bilibili"
cask "docker"
cask "gitter"
cask "iterm2"
cask "keepingyouawake"
cask "licecap"
cask "sourcetree"
cask "spectacle"
