[[snippets]]
  description = "Upgrade Neovim"
  command = "cd $HOME/bin && mv nvim-macos.tar.gz nvim-macos.bak.tar.gz && curl -O -L https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz && rm -rf nvim-osx64 && tar xzf nvim-macos.tar.gz"
  output = ""

[[snippets]]
  description = "Makefile for Go"
  command = "curl -O https://gist.githubusercontent.com/fannheyward/d58f66c91f7f052e0a27acf2d700103a/raw/Makefile"
  output = ""

[[snippets]]
  description = "Upgrade gopls"
  command = "cd && go get -u golang.org/x/tools/cmd/gopls"
  output = ""

[[snippets]]
  description = "Upgrade bingo gopls"
  command = "pushd $HOME/src/tools && git pull && git fetch go && git merge --no-edit go/master && cd cmd/gopls && go install && popd"
  output = ""
