#:schema https://developers.openai.com/codex/config-schema.json

model = "gpt-6-astra"
model_provider = "openrouter"
model_reasoning_effort = "xhigh"
model_reasoning_summary = "concise"
model_context_window = 1000000
model_auto_compact_token_limit = 900000
model_verbosity = "low"
web_search = "live"
personality = "pragmatic"

[features]
context_management = true
collaboration_modes = true
default_mode_request_user_input = true
shell_snapshot = true
js_repl = false
hooks = true
memories = true

[model_providers.openrouter]
name = "openrouter"
base_url = "https://openrouter.ai/api/v1"
env_key = "OPENROUTER_API_KEY"
wire_api = "responses"

[model_providers.cliproxyapi]
name = "cliproxyapi"
base_url = "http://127.0.0.1:8317/v1"
wire_api = "responses"

[tui.model_availability_nux]
gpt-6-sol = 4
gpt-6-astra = 4

[marketplaces.openai-bundled]
source_type = "local"
source = "/Users/fannheyward/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
source_type = "local"
source = "/Users/fannheyward/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."codex-app-tools@openai-bundled"]
enabled = true

[plugins."unified-computer-use@openai-bundled"]
enabled = true

[desktop]
conversationDetailMode = "STEPS_COMMANDS"
ambient-suggestions-enabled = false
git-branch-prefix = "fannheyward/"
followUpQueueMode = "queue"
dock-icon-preference = "codex-system"
enabled-reasoning-efforts = ["low", "medium", "high", "xhigh", "max", "ultra"]
git-worktree-root = "/Users/fannheyward/worktrees"
localeOverride = "en-US"
computerUseAlwaysHidePictureInPicture = true
show-context-window-usage = true

[desktop.open-in-target-preferences]
global = "ghostty"

[memories]
generate_memories = true
use_memories = true

[notice]
hide_rate_limit_model_nudge = true
